title: 照片墙
subtitle: Slow Down
description: 生活的每一刻都值得珍惜
cover: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/IMG_7586.4e91my1ve140.17iz0sa56gik.webp'
author: KaI-tsit

footer_logo: 
  use: self
  self:
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://KaI-tsit.github.io/gallery
root: /gallery

photography_page:
  slogan: true
  slogan_descr: 'QQ gallery'
  travel_slogan: true
  travel_slogan_descr: 'KaI-tsit'

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: 

follow_challenge:
  feedId: ""
  userId: ""

nav:
  地图:
    link: /gallery/location
    icon: local-two
  归档: 
    link: https://KaI-tsit.github.io
    icon: inbox
  随机:
    link: /gallery/random
    icon: pic
  # 查询:
  #   link: /gallery/query
  #   icon: history-query
  状态监控:
    link: /gallery/status
    icon: list-view
  时间线:
    link: /gallery/grid-all
    icon: grid-nine

thumbnail_url: https://cdn.jsdelivr.net/gh/KaI-tsit/gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/KaI-tsit/gallery@master
backup_base_url: https://raw.githubusercontent.com/KaI-tsit/gallery/master
backup_thumbnail_url: https://raw.githubusercontent.com/KaI-tsit/gallery/thumbnail/